# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    yara_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

yara_arm_controller:
  ros__parameters:
    joints:
      - yara_joint_1
      - yara_joint_2
      - yara_joint_3
      - yara_joint_4
      - yara_joint_5
    command_interfaces:
      - position
      - velocity
      - effort
    state_interfaces:
      - position
      - velocity
      - effort
    allow_nonzero_velocity_at_trajectory_end: true